language: node_js

node_js:
    - "node"

before_script:
    - npm install
    - npm install coveralls

script:
    - npm run lint
    - npm run build
    - npm test

after_success:
    - npm run coverage
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    - sh -x ./ci/update_pages.sh

