language: node_js

node_js:
    - "node"

before_script:
    - npm install
    - npm install coveralls

script:
    - npm run lint
    - npm run build:all
    - npm run docs:md
    - npm test

after_success:
    - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sh ./ci/upload_arts.sh; fi

